server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://c:cleanpassword@localhost:27017
      database: boot-mongodb

springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true

  override-with-generic-response: false
  packages-to-exclude: /**/api-docs,/swagger-resources/**
  swagger-ui:
    path: /

