server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://c:cleanpassword@localhost:27017
      database: boot-mongodb
  application:
    name: cash-box
  kafka:
    topic: topic
    othertopic: othertopic
    producer:
      client-id: ${spring.application.name}-producer-stream
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    consumer:
      client-id-prefix: ${spring.application.name}-consumer-stream
      group-id: kafka_streams_cash_box
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      isolation-level: read_committed
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true

  override-with-generic-response: false
  packages-to-exclude: /**/api-docs,/swagger-resources/**
  swagger-ui:
    path: /

